name: coin_aggregator
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.22.0"
  
dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.5
  dice_bear: ^0.1.5
  dio: ^5.4.3+1
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^2.2.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get_it: ^7.2.0
  go_router: ^14.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  retrofit: ^4.1.0


dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  mocktail: ^1.0.4
  retrofit_generator: ^8.1.0
  very_good_analysis: ^5.1.0
  
flutter:
  uses-material-design: true
  generate: true
